### ISSUE TITLE
Por favor indique o link para o trabalho de Melhores praticas(peso 5)

### ISSUE THREAD

**Issue by RafaelGorski** [CamoesEngenhariaDeSoftware/Vinicius-Jos-de-Rocco#1]
@vinizithion 
Por favor indique o link para o trabalho de Melhores praticas(peso 5)

**Comment by vinizithion** [comment]
Oi professor, eu fiz o trabalho com o Vinicius Gustavo. Segue o link do nosso trabalho

https://github.com/CamoesEngenhariaDeSoftware/ViniciusGustavo/blob/master/Boas%20Praticas.pdf

[https://avatars3.githubusercontent.com/u/41393447?s=400&v=4]<https://github.com/CamoesEngenhariaDeSoftware/ViniciusGustavo/blob/master/Boas%20Praticas.pdf>

CamoesEngenhariaDeSoftware/ViniciusGustavo<https://github.com/CamoesEngenhariaDeSoftware/ViniciusGustavo/blob/master/Boas%20Praticas.pdf>
github.com
Repositorio do Aluno Vinicius Gustavo de Oliveira ADS - CamoesEngenhariaDeSoftware/ViniciusGustavo




________________________________
De: Rafael Gorski <notifications@github.com>
Enviado: segunda-feira, 8 de outubro de 2018 14:41:09
Para: CamoesEngenhariaDeSoftware/Vinicius-Jos-de-Rocco
Cc: Vinicius Rocco; Mention
Assunto: [CamoesEngenhariaDeSoftware/Vinicius-Jos-de-Rocco] Por favor indique o link para o trabalho de Melhores praticas(peso 5) (#1)


@vinizithion<https://github.com/vinizithion>
Por favor indique o link para o trabalho de Melhores praticas(peso 5)

**Comment by RafaelGorski** [comment]
ok, vou avaliar e alterar sua nota. Lembrando que a nota nao eh final e ainda falta a ultima apresentacao. Certifique-se que ira apresentar o trabalho dia 19.
